[
  {
    "id": 1,
    "title": "iPhone 15 Pro 256GB",
    "description": "Smartphone con chip A17 Pro, pantalla Super Retina XDR de 6.1 pulgadas, sistema de tres camaras de 48 MP y estructura en titanio. Ideal para fotografia profesional y alto rendimiento.",
    "price": 5499000,
    "discountPercentage": 5,
    "rating": 4.8,
    "stock": 18,
    "brand": "Apple",
    "category": "Celulares",
    "thumbnail": "assets/img/smartphone.svg",
    "images": ["assets/img/smartphone.svg"]
  },
  {
    "id": 2,
    "title": "Samsung Galaxy S24 Ultra",
    "description": "Telefono insignia con pantalla Dynamic AMOLED 2X de 6.8 pulgadas, S Pen integrado, camara de 200 MP y funciones de inteligencia artificial Galaxy AI.",
    "price": 5199000,
    "discountPercentage": 8,
    "rating": 4.7,
    "stock": 12,
    "brand": "Samsung",
    "category": "Celulares",
    "thumbnail": "assets/img/smartphone.svg",
    "images": ["assets/img/smartphone.svg"]
  },
  {
    "id": 3,
    "title": "Xiaomi Redmi Note 13 Pro",
    "description": "Gama media con camara principal de 200 MP, pantalla AMOLED de 120 Hz y carga rapida de 67 W. Excelente relacion precio-rendimiento.",
    "price": 1099000,
    "discountPercentage": 12,
    "rating": 4.5,
    "stock": 40,
    "brand": "Xiaomi",
    "category": "Celulares",
    "thumbnail": "assets/img/smartphone.svg",
    "images": ["assets/img/smartphone.svg"]
  },
  {
    "id": 4,
    "title": "Motorola Edge 50",
    "description": "Diseno delgado con pantalla pOLED curva, camara de 50 MP con estabilizacion optica y bateria de larga duracion con carga TurboPower.",
    "price": 1499000,
    "discountPercentage": 10,
    "rating": 4.3,
    "stock": 25,
    "brand": "Motorola",
    "category": "Celulares",
    "thumbnail": "assets/img/smartphone.svg",
    "images": ["assets/img/smartphone.svg"]
  },
  {
    "id": 5,
    "title": "MacBook Air M3 13 pulgadas",
    "description": "Portatil ultraligero con chip Apple M3, 8 nucleos de CPU, pantalla Liquid Retina y hasta 18 horas de bateria. Silencioso y sin ventilador.",
    "price": 6299000,
    "discountPercentage": 4,
    "rating": 4.9,
    "stock": 9,
    "brand": "Apple",
    "category": "Portatiles",
    "thumbnail": "assets/img/laptop.svg",
    "images": ["assets/img/laptop.svg"]
  },
  {
    "id": 6,
    "title": "Asus VivoBook 15",
    "description": "Portatil con procesador Intel Core i5, 16 GB de RAM, SSD de 512 GB y pantalla Full HD de 15.6 pulgadas. Ideal para estudio y trabajo diario.",
    "price": 2399000,
    "discountPercentage": 7,
    "rating": 4.4,
    "stock": 15,
    "brand": "Asus",
    "category": "Portatiles",
    "thumbnail": "assets/img/laptop.svg",
    "images": ["assets/img/laptop.svg"]
  },
  {
    "id": 7,
    "title": "Lenovo IdeaPad Slim 5",
    "description": "Equipo con procesador AMD Ryzen 7, 16 GB de RAM y SSD de 1 TB. Chasis metalico y teclado retroiluminado para productividad.",
    "price": 2799000,
    "discountPercentage": 9,
    "rating": 4.5,
    "stock": 11,
    "brand": "Lenovo",
    "category": "Portatiles",
    "thumbnail": "assets/img/laptop.svg",
    "images": ["assets/img/laptop.svg"]
  },
  {
    "id": 8,
    "title": "HP Pavilion 14",
    "description": "Portatil compacto con Intel Core i7, 16 GB de RAM, pantalla IPS de 14 pulgadas y diseno liviano para movilidad.",
    "price": 2599000,
    "discountPercentage": 6,
    "rating": 4.2,
    "stock": 13,
    "brand": "HP",
    "category": "Portatiles",
    "thumbnail": "assets/img/laptop.svg",
    "images": ["assets/img/laptop.svg"]
  },
  {
    "id": 9,
    "title": "iPad Air 11 pulgadas M2",
    "description": "Tableta con chip M2, pantalla Liquid Retina, compatibilidad con Apple Pencil Pro y Magic Keyboard. Potente para creatividad y estudio.",
    "price": 3199000,
    "discountPercentage": 5,
    "rating": 4.7,
    "stock": 14,
    "brand": "Apple",
    "category": "Tablets",
    "thumbnail": "assets/img/tablet.svg",
    "images": ["assets/img/tablet.svg"]
  },
  {
    "id": 10,
    "title": "Samsung Galaxy Tab S9",
    "description": "Tableta con pantalla Dynamic AMOLED de 11 pulgadas, S Pen incluido, resistencia al agua IP68 y procesador Snapdragon 8 Gen 2.",
    "price": 2899000,
    "discountPercentage": 8,
    "rating": 4.6,
    "stock": 10,
    "brand": "Samsung",
    "category": "Tablets",
    "thumbnail": "assets/img/tablet.svg",
    "images": ["assets/img/tablet.svg"]
  },
  {
    "id": 11,
    "title": "Sony WH-1000XM5",
    "description": "Audifonos de diadema con cancelacion de ruido lider en la industria, sonido de alta resolucion y hasta 30 horas de bateria.",
    "price": 1699000,
    "discountPercentage": 10,
    "rating": 4.8,
    "stock": 20,
    "brand": "Sony",
    "category": "Audio",
    "thumbnail": "assets/img/headphones.svg",
    "images": ["assets/img/headphones.svg"]
  },
  {
    "id": 12,
    "title": "JBL Tune 770NC",
    "description": "Audifonos inalambricos con cancelacion activa de ruido, sonido JBL Pure Bass y 70 horas de autonomia con carga rapida.",
    "price": 549000,
    "discountPercentage": 15,
    "rating": 4.4,
    "stock": 35,
    "brand": "JBL",
    "category": "Audio",
    "thumbnail": "assets/img/headphones.svg",
    "images": ["assets/img/headphones.svg"]
  },
  {
    "id": 13,
    "title": "Apple AirPods Pro 2",
    "description": "Audifonos in-ear con cancelacion activa de ruido, audio espacial personalizado y estuche de carga MagSafe con USB-C.",
    "price": 999000,
    "discountPercentage": 6,
    "rating": 4.7,
    "stock": 28,
    "brand": "Apple",
    "category": "Audio",
    "thumbnail": "assets/img/headphones.svg",
    "images": ["assets/img/headphones.svg"]
  },
  {
    "id": 14,
    "title": "Apple Watch Series 9",
    "description": "Reloj inteligente con chip S9, pantalla Retina siempre activa, gesto de doble toque, sensor de oxigeno en sangre y GPS.",
    "price": 1899000,
    "discountPercentage": 5,
    "rating": 4.6,
    "stock": 16,
    "brand": "Apple",
    "category": "Wearables",
    "thumbnail": "assets/img/watch.svg",
    "images": ["assets/img/watch.svg"]
  },
  {
    "id": 15,
    "title": "Samsung Galaxy Watch6",
    "description": "Smartwatch con pantalla Super AMOLED, monitoreo avanzado de sueno, medicion de composicion corporal y resistencia al agua.",
    "price": 1199000,
    "discountPercentage": 9,
    "rating": 4.4,
    "stock": 19,
    "brand": "Samsung",
    "category": "Wearables",
    "thumbnail": "assets/img/watch.svg",
    "images": ["assets/img/watch.svg"]
  },
  {
    "id": 16,
    "title": "Xiaomi Smart Band 8",
    "description": "Banda de actividad con pantalla AMOLED de 1.62 pulgadas, mas de 150 modos deportivos, monitor de ritmo cardiaco y 16 dias de bateria.",
    "price": 159000,
    "discountPercentage": 12,
    "rating": 4.3,
    "stock": 50,
    "brand": "Xiaomi",
    "category": "Wearables",
    "thumbnail": "assets/img/watch.svg",
    "images": ["assets/img/watch.svg"]
  },
  {
    "id": 17,
    "title": "Canon EOS R50",
    "description": "Camara mirrorless APS-C de 24.2 MP con grabacion de video 4K, enfoque automatico inteligente y conectividad inalambrica.",
    "price": 3499000,
    "discountPercentage": 6,
    "rating": 4.7,
    "stock": 7,
    "brand": "Canon",
    "category": "Camaras",
    "thumbnail": "assets/img/camera.svg",
    "images": ["assets/img/camera.svg"]
  },
  {
    "id": 18,
    "title": "GoPro HERO12 Black",
    "description": "Camara de accion con video 5.3K, estabilizacion HyperSmooth 6.0, resistencia al agua hasta 10 metros y transmision en vivo.",
    "price": 1899000,
    "discountPercentage": 8,
    "rating": 4.6,
    "stock": 12,
    "brand": "GoPro",
    "category": "Camaras",
    "thumbnail": "assets/img/camera.svg",
    "images": ["assets/img/camera.svg"]
  },
  {
    "id": 19,
    "title": "LG OLED C4 55 pulgadas",
    "description": "Televisor OLED 4K con procesador a9 Gen7, 120 Hz, Dolby Vision y Dolby Atmos. Negros perfectos y excelente para gaming.",
    "price": 5999000,
    "discountPercentage": 7,
    "rating": 4.9,
    "stock": 6,
    "brand": "LG",
    "category": "Televisores",
    "thumbnail": "assets/img/tv.svg",
    "images": ["assets/img/tv.svg"]
  },
  {
    "id": 20,
    "title": "Samsung Crystal UHD 50 pulgadas",
    "description": "Televisor 4K con tecnologia Crystal Processor, HDR, modo juego y plataforma Tizen con aplicaciones de streaming integradas.",
    "price": 1999000,
    "discountPercentage": 10,
    "rating": 4.3,
    "stock": 14,
    "brand": "Samsung",
    "category": "Televisores",
    "thumbnail": "assets/img/tv.svg",
    "images": ["assets/img/tv.svg"]
  },
  {
    "id": 21,
    "title": "PlayStation 5 Slim",
    "description": "Consola de nueva generacion con SSD ultrarrapido, graficos en 4K, control DualSense con respuesta haptica y lector de discos.",
    "price": 2799000,
    "discountPercentage": 3,
    "rating": 4.9,
    "stock": 8,
    "brand": "Sony",
    "category": "Gaming",
    "thumbnail": "assets/img/console.svg",
    "images": ["assets/img/console.svg"]
  },
  {
    "id": 22,
    "title": "Xbox Series X",
    "description": "Consola con 12 teraflops de potencia, 1 TB SSD, soporte para 4K a 120 FPS y retrocompatibilidad con miles de titulos.",
    "price": 2699000,
    "discountPercentage": 5,
    "rating": 4.8,
    "stock": 9,
    "brand": "Microsoft",
    "category": "Gaming",
    "thumbnail": "assets/img/console.svg",
    "images": ["assets/img/console.svg"]
  },
  {
    "id": 23,
    "title": "Logitech MX Master 3S",
    "description": "Mouse inalambrico de precision con sensor de 8000 DPI, clics silenciosos, scroll MagSpeed y conexion para hasta tres equipos.",
    "price": 419000,
    "discountPercentage": 8,
    "rating": 4.7,
    "stock": 30,
    "brand": "Logitech",
    "category": "Accesorios",
    "thumbnail": "assets/img/accessory.svg",
    "images": ["assets/img/accessory.svg"]
  },
  {
    "id": 24,
    "title": "Monitor LG UltraGear 27 pulgadas",
    "description": "Monitor gamer QHD con panel IPS de 165 Hz, 1 ms de respuesta, compatibilidad con NVIDIA G-Sync y AMD FreeSync Premium.",
    "price": 1299000,
    "discountPercentage": 9,
    "rating": 4.5,
    "stock": 17,
    "brand": "LG",
    "category": "Monitores",
    "thumbnail": "assets/img/monitor.svg",
    "images": ["assets/img/monitor.svg"]
  }
]
